// Copyright 2025 The Pigweed Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// AUTOGENERATED - DO NOT EDIT
//
// This file was generated by generate_apply_macros.py.
// To make changes, update the script and run it to generate this file.
#pragma once

// clang-format off
#define _PW_ADD0_0 0
#define _PW_ADD0_1 1
#define _PW_ADD0_2 2
#define _PW_ADD0_3 3
#define _PW_ADD0_4 4
#define _PW_ADD0_5 5
#define _PW_ADD0_6 6
#define _PW_ADD0_7 7
#define _PW_ADD0_8 8
#define _PW_ADD0_9 9
#define _PW_ADD0_10 10
#define _PW_ADD0_11 11
#define _PW_ADD0_12 12
#define _PW_ADD0_13 13
#define _PW_ADD0_14 14
#define _PW_ADD0_15 15
#define _PW_ADD0_16 16
#define _PW_ADD0_17 17
#define _PW_ADD0_18 18
#define _PW_ADD0_19 19
#define _PW_ADD0_20 20
#define _PW_ADD0_21 21
#define _PW_ADD0_22 22
#define _PW_ADD0_23 23
#define _PW_ADD0_24 24
#define _PW_ADD0_25 25
#define _PW_ADD0_26 26
#define _PW_ADD0_27 27
#define _PW_ADD0_28 28
#define _PW_ADD0_29 29
#define _PW_ADD0_30 30
#define _PW_ADD0_31 31
#define _PW_ADD0_32 32
#define _PW_ADD32_0 32
#define _PW_ADD32_1 33
#define _PW_ADD32_2 34
#define _PW_ADD32_3 35
#define _PW_ADD32_4 36
#define _PW_ADD32_5 37
#define _PW_ADD32_6 38
#define _PW_ADD32_7 39
#define _PW_ADD32_8 40
#define _PW_ADD32_9 41
#define _PW_ADD32_10 42
#define _PW_ADD32_11 43
#define _PW_ADD32_12 44
#define _PW_ADD32_13 45
#define _PW_ADD32_14 46
#define _PW_ADD32_15 47
#define _PW_ADD32_16 48
#define _PW_ADD32_17 49
#define _PW_ADD32_18 50
#define _PW_ADD32_19 51
#define _PW_ADD32_20 52
#define _PW_ADD32_21 53
#define _PW_ADD32_22 54
#define _PW_ADD32_23 55
#define _PW_ADD32_24 56
#define _PW_ADD32_25 57
#define _PW_ADD32_26 58
#define _PW_ADD32_27 59
#define _PW_ADD32_28 60
#define _PW_ADD32_29 61
#define _PW_ADD32_30 62
#define _PW_ADD32_31 63
#define _PW_ADD32_32 64
#define _PW_ADD64_0 64
#define _PW_ADD64_1 65
#define _PW_ADD64_2 66
#define _PW_ADD64_3 67
#define _PW_ADD64_4 68
#define _PW_ADD64_5 69
#define _PW_ADD64_6 70
#define _PW_ADD64_7 71
#define _PW_ADD64_8 72
#define _PW_ADD64_9 73
#define _PW_ADD64_10 74
#define _PW_ADD64_11 75
#define _PW_ADD64_12 76
#define _PW_ADD64_13 77
#define _PW_ADD64_14 78
#define _PW_ADD64_15 79
#define _PW_ADD64_16 80
#define _PW_ADD64_17 81
#define _PW_ADD64_18 82
#define _PW_ADD64_19 83
#define _PW_ADD64_20 84
#define _PW_ADD64_21 85
#define _PW_ADD64_22 86
#define _PW_ADD64_23 87
#define _PW_ADD64_24 88
#define _PW_ADD64_25 89
#define _PW_ADD64_26 90
#define _PW_ADD64_27 91
#define _PW_ADD64_28 92
#define _PW_ADD64_29 93
#define _PW_ADD64_30 94
#define _PW_ADD64_31 95
#define _PW_ADD64_32 96
#define _PW_ADD96_0 96
#define _PW_ADD96_1 97
#define _PW_ADD96_2 98
#define _PW_ADD96_3 99
#define _PW_ADD96_4 100
#define _PW_ADD96_5 101
#define _PW_ADD96_6 102
#define _PW_ADD96_7 103
#define _PW_ADD96_8 104
#define _PW_ADD96_9 105
#define _PW_ADD96_10 106
#define _PW_ADD96_11 107
#define _PW_ADD96_12 108
#define _PW_ADD96_13 109
#define _PW_ADD96_14 110
#define _PW_ADD96_15 111
#define _PW_ADD96_16 112
#define _PW_ADD96_17 113
#define _PW_ADD96_18 114
#define _PW_ADD96_19 115
#define _PW_ADD96_20 116
#define _PW_ADD96_21 117
#define _PW_ADD96_22 118
#define _PW_ADD96_23 119
#define _PW_ADD96_24 120
#define _PW_ADD96_25 121
#define _PW_ADD96_26 122
#define _PW_ADD96_27 123
#define _PW_ADD96_28 124
#define _PW_ADD96_29 125
#define _PW_ADD96_30 126
#define _PW_ADD96_31 127
#define _PW_ADD96_32 128
#define _PW_ADD128_0 128
#define _PW_ADD128_1 129
#define _PW_ADD128_2 130
#define _PW_ADD128_3 131
#define _PW_ADD128_4 132
#define _PW_ADD128_5 133
#define _PW_ADD128_6 134
#define _PW_ADD128_7 135
#define _PW_ADD128_8 136
#define _PW_ADD128_9 137
#define _PW_ADD128_10 138
#define _PW_ADD128_11 139
#define _PW_ADD128_12 140
#define _PW_ADD128_13 141
#define _PW_ADD128_14 142
#define _PW_ADD128_15 143
#define _PW_ADD128_16 144
#define _PW_ADD128_17 145
#define _PW_ADD128_18 146
#define _PW_ADD128_19 147
#define _PW_ADD128_20 148
#define _PW_ADD128_21 149
#define _PW_ADD128_22 150
#define _PW_ADD128_23 151
#define _PW_ADD128_24 152
#define _PW_ADD128_25 153
#define _PW_ADD128_26 154
#define _PW_ADD128_27 155
#define _PW_ADD128_28 156
#define _PW_ADD128_29 157
#define _PW_ADD128_30 158
#define _PW_ADD128_31 159
#define _PW_ADD128_32 160
#define _PW_ADD160_0 160
#define _PW_ADD160_1 161
#define _PW_ADD160_2 162
#define _PW_ADD160_3 163
#define _PW_ADD160_4 164
#define _PW_ADD160_5 165
#define _PW_ADD160_6 166
#define _PW_ADD160_7 167
#define _PW_ADD160_8 168
#define _PW_ADD160_9 169
#define _PW_ADD160_10 170
#define _PW_ADD160_11 171
#define _PW_ADD160_12 172
#define _PW_ADD160_13 173
#define _PW_ADD160_14 174
#define _PW_ADD160_15 175
#define _PW_ADD160_16 176
#define _PW_ADD160_17 177
#define _PW_ADD160_18 178
#define _PW_ADD160_19 179
#define _PW_ADD160_20 180
#define _PW_ADD160_21 181
#define _PW_ADD160_22 182
#define _PW_ADD160_23 183
#define _PW_ADD160_24 184
#define _PW_ADD160_25 185
#define _PW_ADD160_26 186
#define _PW_ADD160_27 187
#define _PW_ADD160_28 188
#define _PW_ADD160_29 189
#define _PW_ADD160_30 190
#define _PW_ADD160_31 191
#define _PW_ADD160_32 192
#define _PW_ADD192_0 192
#define _PW_ADD192_1 193
#define _PW_ADD192_2 194
#define _PW_ADD192_3 195
#define _PW_ADD192_4 196
#define _PW_ADD192_5 197
#define _PW_ADD192_6 198
#define _PW_ADD192_7 199
#define _PW_ADD192_8 200
#define _PW_ADD192_9 201
#define _PW_ADD192_10 202
#define _PW_ADD192_11 203
#define _PW_ADD192_12 204
#define _PW_ADD192_13 205
#define _PW_ADD192_14 206
#define _PW_ADD192_15 207
#define _PW_ADD192_16 208
#define _PW_ADD192_17 209
#define _PW_ADD192_18 210
#define _PW_ADD192_19 211
#define _PW_ADD192_20 212
#define _PW_ADD192_21 213
#define _PW_ADD192_22 214
#define _PW_ADD192_23 215
#define _PW_ADD192_24 216
#define _PW_ADD192_25 217
#define _PW_ADD192_26 218
#define _PW_ADD192_27 219
#define _PW_ADD192_28 220
#define _PW_ADD192_29 221
#define _PW_ADD192_30 222
#define _PW_ADD192_31 223
#define _PW_ADD192_32 224
#define _PW_ADD224_0 224
#define _PW_ADD224_1 225
#define _PW_ADD224_2 226
#define _PW_ADD224_3 227
#define _PW_ADD224_4 228
#define _PW_ADD224_5 229
#define _PW_ADD224_6 230
#define _PW_ADD224_7 231
#define _PW_ADD224_8 232
#define _PW_ADD224_9 233
#define _PW_ADD224_10 234
#define _PW_ADD224_11 235
#define _PW_ADD224_12 236
#define _PW_ADD224_13 237
#define _PW_ADD224_14 238
#define _PW_ADD224_15 239
#define _PW_ADD224_16 240
#define _PW_ADD224_17 241
#define _PW_ADD224_18 242
#define _PW_ADD224_19 243
#define _PW_ADD224_20 244
#define _PW_ADD224_21 245
#define _PW_ADD224_22 246
#define _PW_ADD224_23 247
#define _PW_ADD224_24 248
#define _PW_ADD224_25 249
#define _PW_ADD224_26 250
#define _PW_ADD224_27 251
#define _PW_ADD224_28 252
#define _PW_ADD224_29 253
#define _PW_ADD224_30 254
#define _PW_ADD224_31 255
#define _PW_ADD224_32 256

#define _PW_AD(a, b) _PW_ADD_EXPAND(a, b)
#define _PW_ADD_EXPAND(a, b) _PW_ADD##a##_##b
#define _PW_I(macro, ...) macro(__VA_ARGS__)

#define _PW_AP0(a,b,c,d,e)
#define _PW_AP1(a,b,c,d,e)_PW_I(a, _PW_AD(d,0), c, e)
#define _PW_AP2(a,b,c,d,e,f)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)
#define _PW_AP3(a,b,c,d,e,f,g)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)
#define _PW_AP4(a,b,c,d,e,f,g,h)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)
#define _PW_AP5(a,b,c,d,e,f,g,h,i)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)
#define _PW_AP6(a,b,c,d,e,f,g,h,i,j)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)
#define _PW_AP7(a,b,c,d,e,f,g,h,i,j,k)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)
#define _PW_AP8(a,b,c,d,e,f,g,h,i,j,k,l)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)
#define _PW_AP9(a,b,c,d,e,f,g,h,i,j,k,l,m)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)
#define _PW_AP10(a,b,c,d,e,f,g,h,i,j,k,l,m,n)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)
#define _PW_AP11(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)
#define _PW_AP12(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)
#define _PW_AP13(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)
#define _PW_AP14(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)
#define _PW_AP15(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)
#define _PW_AP16(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)
#define _PW_AP17(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)
#define _PW_AP18(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)
#define _PW_AP19(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)
#define _PW_AP20(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)
#define _PW_AP21(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)
#define _PW_AP22(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)
#define _PW_AP23(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)
#define _PW_AP24(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)
#define _PW_AP25(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)
#define _PW_AP26(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)
#define _PW_AP27(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)
#define _PW_AP28(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)_PW_I(b, _PW_AD(d,26), c)_PW_I(a, _PW_AD(d,27), c, F)
#define _PW_AP29(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)_PW_I(b, _PW_AD(d,26), c)_PW_I(a, _PW_AD(d,27), c, F)_PW_I(b, _PW_AD(d,27), c)_PW_I(a, _PW_AD(d,28), c, G)
#define _PW_AP30(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)_PW_I(b, _PW_AD(d,26), c)_PW_I(a, _PW_AD(d,27), c, F)_PW_I(b, _PW_AD(d,27), c)_PW_I(a, _PW_AD(d,28), c, G)_PW_I(b, _PW_AD(d,28), c)_PW_I(a, _PW_AD(d,29), c, H)
#define _PW_AP31(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)_PW_I(b, _PW_AD(d,26), c)_PW_I(a, _PW_AD(d,27), c, F)_PW_I(b, _PW_AD(d,27), c)_PW_I(a, _PW_AD(d,28), c, G)_PW_I(b, _PW_AD(d,28), c)_PW_I(a, _PW_AD(d,29), c, H)_PW_I(b, _PW_AD(d,29), c)_PW_I(a, _PW_AD(d,30), c, I)
#define _PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(a, _PW_AD(d,0), c, e)_PW_I(b, _PW_AD(d,0), c)_PW_I(a, _PW_AD(d,1), c, f)_PW_I(b, _PW_AD(d,1), c)_PW_I(a, _PW_AD(d,2), c, g)_PW_I(b, _PW_AD(d,2), c)_PW_I(a, _PW_AD(d,3), c, h)_PW_I(b, _PW_AD(d,3), c)_PW_I(a, _PW_AD(d,4), c, i)_PW_I(b, _PW_AD(d,4), c)_PW_I(a, _PW_AD(d,5), c, j)_PW_I(b, _PW_AD(d,5), c)_PW_I(a, _PW_AD(d,6), c, k)_PW_I(b, _PW_AD(d,6), c)_PW_I(a, _PW_AD(d,7), c, l)_PW_I(b, _PW_AD(d,7), c)_PW_I(a, _PW_AD(d,8), c, m)_PW_I(b, _PW_AD(d,8), c)_PW_I(a, _PW_AD(d,9), c, n)_PW_I(b, _PW_AD(d,9), c)_PW_I(a, _PW_AD(d,10), c, o)_PW_I(b, _PW_AD(d,10), c)_PW_I(a, _PW_AD(d,11), c, p)_PW_I(b, _PW_AD(d,11), c)_PW_I(a, _PW_AD(d,12), c, q)_PW_I(b, _PW_AD(d,12), c)_PW_I(a, _PW_AD(d,13), c, r)_PW_I(b, _PW_AD(d,13), c)_PW_I(a, _PW_AD(d,14), c, s)_PW_I(b, _PW_AD(d,14), c)_PW_I(a, _PW_AD(d,15), c, t)_PW_I(b, _PW_AD(d,15), c)_PW_I(a, _PW_AD(d,16), c, u)_PW_I(b, _PW_AD(d,16), c)_PW_I(a, _PW_AD(d,17), c, v)_PW_I(b, _PW_AD(d,17), c)_PW_I(a, _PW_AD(d,18), c, w)_PW_I(b, _PW_AD(d,18), c)_PW_I(a, _PW_AD(d,19), c, x)_PW_I(b, _PW_AD(d,19), c)_PW_I(a, _PW_AD(d,20), c, y)_PW_I(b, _PW_AD(d,20), c)_PW_I(a, _PW_AD(d,21), c, z)_PW_I(b, _PW_AD(d,21), c)_PW_I(a, _PW_AD(d,22), c, A)_PW_I(b, _PW_AD(d,22), c)_PW_I(a, _PW_AD(d,23), c, B)_PW_I(b, _PW_AD(d,23), c)_PW_I(a, _PW_AD(d,24), c, C)_PW_I(b, _PW_AD(d,24), c)_PW_I(a, _PW_AD(d,25), c, D)_PW_I(b, _PW_AD(d,25), c)_PW_I(a, _PW_AD(d,26), c, E)_PW_I(b, _PW_AD(d,26), c)_PW_I(a, _PW_AD(d,27), c, F)_PW_I(b, _PW_AD(d,27), c)_PW_I(a, _PW_AD(d,28), c, G)_PW_I(b, _PW_AD(d,28), c)_PW_I(a, _PW_AD(d,29), c, H)_PW_I(b, _PW_AD(d,29), c)_PW_I(a, _PW_AD(d,30), c, I)_PW_I(b, _PW_AD(d,30), c)_PW_I(a, _PW_AD(d,31), c, J)
#define _PW_AP33(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP1(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP34(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP2(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP35(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP3(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP36(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP4(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP37(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP5(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP38(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP6(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP39(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP7(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP40(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP8(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP41(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP9(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP42(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP10(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP43(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP11(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP44(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP12(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP45(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP13(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP46(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP14(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP47(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP15(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP48(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP16(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP49(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP17(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP50(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP18(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP51(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP19(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP52(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP20(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP53(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP21(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP54(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP22(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP55(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP23(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP56(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP24(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP57(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP25(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP58(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP26(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP59(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP27(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP60(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP28(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP61(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP29(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP62(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP30(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP63(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP31(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP64(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP32(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP65(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP33(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP66(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP34(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP67(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP35(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP68(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP36(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP69(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP37(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP70(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP38(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP71(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP39(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP72(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP40(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP73(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP41(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP74(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP42(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP75(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP43(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP76(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP44(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP77(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP45(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP78(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP46(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP79(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP47(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP80(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP48(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP81(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP49(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP82(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP50(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP83(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP51(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP84(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP52(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP85(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP53(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP86(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP54(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP87(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP55(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP88(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP56(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP89(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP57(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP90(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP58(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP91(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP59(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP92(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP60(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP93(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP61(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP94(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP62(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP95(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP63(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP96(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP64(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP97(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP65(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP98(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP66(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP99(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP67(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP100(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP68(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP101(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP69(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP102(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP70(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP103(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP71(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP104(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP72(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP105(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP73(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP106(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP74(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP107(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP75(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP108(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP76(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP109(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP77(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP110(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP78(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP111(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP79(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP112(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP80(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP113(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP81(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP114(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP82(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP115(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP83(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP116(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP84(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP117(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP85(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP118(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP86(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP119(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP87(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP120(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP88(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP121(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP89(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP122(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP90(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP123(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP91(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP124(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP92(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP125(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP93(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP126(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP94(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP127(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP95(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP128(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP96(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP129(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP97(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP130(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP98(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP131(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP99(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP132(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP100(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP133(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP101(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP134(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP102(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP135(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP103(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP136(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP104(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP137(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP105(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP138(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP106(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP139(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP107(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP140(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP108(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP141(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP109(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP142(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP110(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP143(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP111(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP144(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP112(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP145(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP113(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP146(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP114(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP147(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP115(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP148(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP116(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP149(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP117(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP150(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP118(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP151(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP119(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP152(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP120(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP153(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP121(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP154(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP122(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP155(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP123(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP156(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP124(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP157(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP125(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP158(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP126(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP159(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP127(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP160(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP128(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP161(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP129(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP162(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP130(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP163(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP131(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP164(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP132(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP165(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP133(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP166(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP134(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP167(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP135(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP168(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP136(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP169(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP137(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP170(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP138(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP171(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP139(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP172(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP140(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP173(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP141(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP174(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP142(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP175(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP143(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP176(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP144(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP177(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP145(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP178(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP146(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP179(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP147(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP180(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP148(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP181(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP149(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP182(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP150(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP183(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP151(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP184(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP152(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP185(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP153(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP186(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP154(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP187(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP155(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP188(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP156(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP189(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP157(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP190(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP158(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP191(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP159(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP192(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP160(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP193(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP161(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP194(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP162(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP195(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP163(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP196(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP164(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP197(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP165(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP198(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP166(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP199(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP167(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP200(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP168(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP201(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP169(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP202(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP170(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP203(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP171(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP204(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP172(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP205(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP173(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP206(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP174(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP207(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP175(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP208(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP176(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP209(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP177(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP210(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP178(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP211(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP179(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP212(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP180(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP213(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP181(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP214(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP182(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP215(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP183(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP216(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP184(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP217(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP185(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP218(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP186(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP219(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP187(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP220(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP188(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP221(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP189(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP222(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP190(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP223(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP191(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP224(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP192(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP225(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP193(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP226(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP194(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP227(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP195(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP228(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP196(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP229(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP197(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP230(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP198(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP231(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP199(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP232(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP200(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP233(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP201(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP234(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP202(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP235(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP203(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP236(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP204(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP237(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP205(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP238(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP206(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP239(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP207(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP240(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP208(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP241(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP209(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP242(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP210(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP243(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP211(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP244(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP212(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP245(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP213(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP246(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP214(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP247(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP215(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP248(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP216(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP249(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP217(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP250(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP218(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP251(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP219(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP252(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP220(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP253(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP221(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP254(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP222(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP255(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP223(a,b,c,_PW_AD(d,32),__VA_ARGS__)
#define _PW_AP256(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,...)_PW_AP32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)_PW_I(b, _PW_AD(d,31), c)_PW_AP224(a,b,c,_PW_AD(d,32),__VA_ARGS__)

